// AUTO-GENERATED by scripts/build-venues-index.ts — DO NOT EDIT
// Generated at: 2026-02-13T21:26:17.836Z

import type { Venue } from "./types";

export const venues: Venue[] = [
  {
    "slug": "cheongdam-h2o",
    "nameKo": "청담H2O나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 청담동",
    "phone": "010-5655-4866",
    "themes": [
      "강남",
      "클럽",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "하우스"
    ],
    "priceMin": 40000,
    "priceMax": 80000,
    "dressCode": "스마트캐주얼 이상 (드레스코드 엄격)",
    "parking": true,
    "beginnerFriendly": false,
    "summary": "강남 청담동의 프리미엄 나이트클럽. 세련된 인테리어와 하이엔드 분위기로, 20~30대 직장인 중심의 고급 클러빙 문화를 이끌고 있습니다.",
    "tips": [
      "드레스코드가 엄격한 편 — 정장/원피스 권장",
      "예약 없이 가면 대기 시간이 길 수 있음",
      "테이블 예약 시 최소 주류 주문 필요",
      "발레파킹 가능 (유료)",
      "첫 방문이라면 바 구역에서 분위기 파악 후 이동"
    ],
    "lastVerifiedAt": "2025-12-20",
    "legacyPaths": [
      "/d/"
    ],
    "operatingHours": "금·토 22:00~05:00",
    "peakTime": "00:00~02:00",
    "bodyContent": "청담H2O나이트는 서울 강남구 청담동에 위치한 프리미엄 나이트클럽입니다."
  },
  {
    "slug": "ilsan-shampoo",
    "nameKo": "일산샴푸나이트",
    "region": "경기",
    "city": "고양",
    "address": "경기도 고양시 일산서구",
    "kakao": "besta12",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "캐주얼 (깔끔하게)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "일산 지역의 대표적인 7080 소셜댄스 나이트클럽. 쾌적한 실내 환경과 넓은 플로어가 특징이며, 경기 북부 이용객들에게 인기입니다.",
    "tips": [
      "일산 서구에서 접근 편리",
      "주차 공간 확보되어 있음",
      "처음이면 위치·교통 안내를 사전에 확인",
      "시간대별 분위기가 다르니 참고",
      "제휴문의는 카카오톡 besta12"
    ],
    "lastVerifiedAt": "2025-12-11",
    "legacyPaths": [
      "/h/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "22:30~00:30",
    "bodyContent": "일산샴푸나이트는 경기도 고양시 일산에 위치한 7080 나이트클럽입니다."
  },
  {
    "slug": "incheon-arabian",
    "nameKo": "인천아라비안나이트",
    "region": "인천",
    "city": "인천",
    "address": "인천광역시 부평구",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "팝"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "캐주얼 (깔끔하게)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "인천 부평 지역의 대표적인 7080 나이트클럽. 이동 경로, 예산, 에티켓까지 체계적으로 안내하며, 초보 방문객도 편하게 이용할 수 있습니다.",
    "tips": [
      "부평역에서 접근 편리",
      "이동·예산·에티켓·귀가까지 단계별로 확인",
      "예산은 3~4만원 정도",
      "깔끔한 캐주얼 복장이면 충분",
      "첫 방문이면 일찍 도착하는 것이 좋음"
    ],
    "lastVerifiedAt": "2025-12-18",
    "legacyPaths": [
      "/k/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "23:00~01:00",
    "bodyContent": "인천아라비안나이트는 인천광역시 부평구에 위치한 7080 나이트클럽입니다."
  },
  {
    "slug": "indeokwon-kookbingwan",
    "nameKo": "인덕원국빈관나이트",
    "region": "경기",
    "city": "안양",
    "address": "경기도 안양시 동안구 인덕원",
    "kakao": "besta12",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "인덕원역 인근에 위치한 7080 소셜댄스 나이트클럽. 대중교통 접근성이 뛰어나고 주차도 가능해 경기 남부 지역 이용객에게 인기입니다.",
    "tips": [
      "4호선 인덕원역에서 도보 이동 가능",
      "주차 공간 있으나 사전에 확인 추천",
      "처음이면 21시 초반에 도착하는 것이 여유로움",
      "주변 상권과 연결되어 2차 이동도 편리",
      "제휴문의는 카카오톡 besta12"
    ],
    "lastVerifiedAt": "2025-12-12",
    "legacyPaths": [
      "/e/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "22:30~00:30",
    "bodyContent": "인덕원국빈관나이트는 경기도 안양시 인덕원에 위치한 7080 나이트클럽입니다."
  },
  {
    "slug": "paju-skydome",
    "nameKo": "파주야당스카이돔나이트",
    "region": "경기",
    "city": "파주",
    "address": "경기도 파주시 야당동",
    "phone": "010-8255-3509",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "팝"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "캐주얼 (깔끔하게)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "파주 야당동의 대형 나이트클럽. 넓은 스카이돔 구조의 홀과 라운지 구역이 분리되어 있어 목적에 맞는 공간 선택이 가능합니다.",
    "tips": [
      "친구 모임이면 라운지 구역에서 시작 추천",
      "메인 플로어 외에 소음이 낮은 구역 존재",
      "자가용 이용이 편리 — 주차장 완비",
      "금요일보다 토요일이 분위기가 더 좋음",
      "도착 후 라운지에서 적응 → 메인 홀 이동 순서 추천"
    ],
    "lastVerifiedAt": "2025-12-14",
    "legacyPaths": [
      "/f/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "22:00~00:00",
    "bodyContent": "파주야당스카이돔나이트는 경기도 파주시 야당동에 위치한 대형 7080 나이트클럽입니다."
  },
  {
    "slug": "sangbong-hankookgwan",
    "nameKo": "상봉동한국관나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 중랑구 상봉동",
    "kakao": "besta12",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 중랑구 상봉동에 위치한 7080 소셜댄스 나이트클럽. 상봉역 인근으로 대중교통 접근성이 뛰어나며, 다양한 연령대가 즐기는 친근한 분위기가 특징입니다.",
    "tips": [
      "상봉역에서 도보 이동 가능",
      "처음이면 21시 초반 도착 권장",
      "라운지 구역에서 먼저 분위기 적응",
      "주차는 인근 공영주차장 이용",
      "제휴문의는 카카오톡 besta12"
    ],
    "lastVerifiedAt": "2026-01-20",
    "legacyPaths": [
      "/j/",
      "/n/",
      "/o/",
      "/p/",
      "/q/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "22:30~00:30",
    "bodyContent": "상봉동한국관나이트는 서울 중랑구 상봉동에 위치한 7080 나이트클럽입니다."
  },
  {
    "slug": "sinlim-grandprix",
    "nameKo": "신림그랑프리나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 관악구 신림동",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "캐주얼 가능 (깔끔하게)",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "신림역 인근의 대표적인 7080 나이트클럽. 접근성이 뛰어나고, 처음 방문하는 사람도 편하게 즐길 수 있는 분위기입니다.",
    "tips": [
      "신림역 도보 5분 이내 접근 가능",
      "복장은 깔끔한 캐주얼이면 충분",
      "예산은 3~4만원 정도 준비",
      "첫 방문이면 일찍 도착해서 자리 잡는 것 추천",
      "주차는 인근 공영주차장 이용"
    ],
    "lastVerifiedAt": "2025-12-10",
    "legacyPaths": [
      "/c/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "23:00~01:00",
    "bodyContent": "신림그랑프리나이트는 서울 관악구 신림동에 위치한 7080 분위기의 나이트클럽입니다."
  },
  {
    "slug": "suwon-chance-dome",
    "nameKo": "수원찬스돔나이트",
    "region": "경기",
    "city": "수원",
    "address": "경기도 수원시 팔달구 인계동",
    "phone": "010-9354-1323",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼 (깔끔한 복장 권장)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "수원 인계동에 위치한 7080 소셜댄스 중심 나이트클럽. 넓은 플로어와 라이브 밴드가 특징이며, 중장년층에게 인기가 높습니다.",
    "tips": [
      "금요일보다 토요일이 더 붐빕니다",
      "22시 이전 입장 시 대기 없이 입장 가능",
      "주차장이 있으나 주말에는 일찍 차는 편",
      "첫 방문이라면 라운지 구역에서 먼저 적응 추천",
      "드레스코드는 엄격하지 않으나 슬리퍼/반바지 비추천"
    ],
    "lastVerifiedAt": "2025-12-15",
    "legacyPaths": [
      "/b/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "23:00~01:00",
    "bodyContent": "수원찬스돔나이트는 수원 인계동 상권 중심부에 위치한 7080 컨셉의 소셜댄스 나이트클럽입니다."
  },
  {
    "slug": "ulsan-champion",
    "nameKo": "울산챔피언나이트",
    "region": "경남",
    "city": "울산",
    "address": "울산광역시 남구 중심 상권",
    "phone": "010-5653-0069",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "팝"
    ],
    "priceMin": 25000,
    "priceMax": 40000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "울산 남구 중심 상권에 위치한 대표적인 7080 나이트클럽. 울산 지역 야간 엔터테인먼트의 중심지로, 넓은 플로어와 체계적인 공간 설계가 특징입니다.",
    "tips": [
      "울산 남구 중심 상권에서 접근 용이",
      "대중교통보다 자가용 이용이 편리",
      "시간대별 분위기 차이가 큰 편",
      "23시 이후가 메인 타임",
      "주차 공간 확보되어 있음"
    ],
    "lastVerifiedAt": "2025-12-08",
    "legacyPaths": [
      "/g/"
    ],
    "operatingHours": "금·토 21:00~03:00",
    "peakTime": "23:00~01:00",
    "bodyContent": "울산챔피언나이트는 울산광역시 남구에 위치한 7080 나이트클럽입니다."
  }
];

export const regions = ["경기","경남","서울","인천"] as const;

export const citiesByRegion: Record<string, string[]> = {
  "경기": [
    "고양",
    "안양",
    "파주",
    "수원"
  ],
  "경남": [
    "울산"
  ],
  "서울": [
    "서울"
  ],
  "인천": [
    "인천"
  ]
};

export const allThemes = ["7080","강남","라운지","소셜댄스","클럽"] as const;

export const legacyRedirects: Record<string, string> = {
  "/d/": "/club/cheongdam-h2o/",
  "/h/": "/club/ilsan-shampoo/",
  "/k/": "/club/incheon-arabian/",
  "/e/": "/club/indeokwon-kookbingwan/",
  "/f/": "/club/paju-skydome/",
  "/j/": "/club/sangbong-hankookgwan/",
  "/n/": "/club/sangbong-hankookgwan/",
  "/o/": "/club/sangbong-hankookgwan/",
  "/p/": "/club/sangbong-hankookgwan/",
  "/q/": "/club/sangbong-hankookgwan/",
  "/c/": "/club/sinlim-grandprix/",
  "/b/": "/club/suwon-chance-dome/",
  "/g/": "/club/ulsan-champion/"
};
