// AUTO-GENERATED by scripts/build-venues-index.ts — DO NOT EDIT
// Generated at: 2026-02-13T23:06:33.676Z

import type { Venue } from "./types";

export const venues: Venue[] = [
  {
    "slug": "arju-lounge",
    "nameKo": "아르쥬라운지",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 압구정로데오 (문의 시 안내)",
    "lat": 37.527,
    "lng": 127.039,
    "phone": "010-9042-4810",
    "themes": [
      "라운지",
      "감성주점"
    ],
    "genres": [
      "팝",
      "R&B",
      "힙합"
    ],
    "priceMin": 100000,
    "priceMax": 500000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 강남에 위치한 프리미엄 감성 라운지. 고급스러운 인테리어와 프라이빗한 분위기에서 양주와 칵테일을 즐길 수 있는 핫플레이스입니다.",
    "tips": [
      "MD 정민: 010-9042-4810",
      "예약 필수 — 사전 문의 권장"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "아르쥬라운지는 서울 강남에 위치한 프리미엄 감성 라운지입니다."
  },
  {
    "slug": "busan-asiad",
    "nameKo": "부산아시아드나이트",
    "region": "부산",
    "city": "부산",
    "address": "부산광역시 동래구 온천장로107번길 32 B1~B2 (농심호텔)",
    "lat": 35.0516,
    "lng": 129.079,
    "phone": "051-997-8888",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "부산 동래구 온천장에 위치한 부산 대표 나이트클럽. 농심호텔 지하 1~2층에 걸친 대규모 시설로, 부산 최고의 부킹 나이트로 유명합니다.",
    "tips": [
      "농심호텔 지하 1~2층",
      "주차 가능",
      "웨이터 따봉: 010-2389-7365",
      "웨이터 권상우: 010-5117-3618",
      "대표전화: 051-997-8888"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "부산아시아드나이트는 부산 동래구 온천장로107번길 32에 위치한 나이트클럽입니다."
  },
  {
    "slug": "busan-mul",
    "nameKo": "부산물나이트",
    "region": "부산",
    "city": "부산",
    "address": "부산광역시 연제구 연산동 목화예시장 6~7층",
    "lat": 35.1812,
    "lng": 129.078,
    "phone": "010-5877-9664",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "부산 연제구 연산동 목화예시장 6~7층에 위치한 나이트클럽. 2개 층에 걸친 넓은 공간에서 7080 음악과 트로트를 즐길 수 있으며, 부산에서 물이 좋기로 유명합니다.",
    "tips": [
      "목화예시장 6~7층",
      "주차 가능",
      "웨이터 박지성: 010-8558-1212",
      "웨이터 만수르: 010-2197-5536",
      "웨이터 박찬호: 010-4892-7403",
      "예약문의: 010-5877-9664"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "부산물나이트는 부산 연제구 연산동 목화예시장 6~7층에 위치한 나이트클럽입니다."
  },
  {
    "slug": "cheonan-stardom",
    "nameKo": "천안스타돔나이트",
    "region": "충남",
    "city": "천안",
    "address": "충청남도 천안시 서북구 성정공원1길 21",
    "lat": 36.8198,
    "lng": 127.156,
    "phone": "041-523-9700",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "충남 천안시 서북구에 위치한 천안 대표 나이트클럽. 넓은 홀과 다양한 룸을 갖추고 있으며, 7080 음악부터 EDM까지 폭넓은 장르를 즐길 수 있습니다.",
    "tips": [
      "천안시 서북구 성정공원1길 21",
      "주차 가능",
      "웨이터 레모나: 010-3018-1001",
      "대표전화: 041-523-9700"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "천안스타돔나이트는 충남 천안시 서북구 성정공원1길 21에 위치한 나이트클럽입니다."
  },
  {
    "slug": "cheongdam-h2o",
    "nameKo": "청담H2O나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 청담동 53-8 리베라호텔 B1",
    "lat": 37.5247,
    "lng": 127.047,
    "phone": "010-7404-6603",
    "themes": [
      "강남",
      "클럽",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "하우스"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "스마트캐주얼 이상 (드레스코드 엄격)",
    "parking": true,
    "beginnerFriendly": false,
    "summary": "강남 청담동 리베라호텔 지하에 위치한 프리미엄 나이트클럽. 예약제로 운영되며, 룸/부스 예약은 사전 연락 필수. 20~30대 직장인 중심의 고급 클러빙 문화를 이끌고 있습니다.",
    "tips": [
      "리베라호텔 지하 1층에 위치",
      "예약제 운영 — 사전 전화 필수: 010-7404-6603",
      "드레스코드 엄격 — 정장/원피스 권장",
      "테이블/부스/룸 예약 시 최소 주류 주문 필요",
      "발레파킹 가능 (유료)",
      "웨이터 부킹맨: 010-5500-6140",
      "웨이터 뻐꾸기: 010-5368-2596",
      "웨이터 토마토: 010-5877-7275",
      "웨이터 비트코인: 010-9453-5115"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/d/"
    ],
    "operatingHours": "금·토 22:00~05:00 (예약제)",
    "peakTime": "00:00~02:00",
    "bodyContent": "청담H2O나이트는 서울 강남구 청담동 리베라호텔 B1에 위치한 프리미엄 나이트클럽입니다."
  },
  {
    "slug": "color-lounge",
    "nameKo": "컬러라운지",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 압구정로데오 (압구정로데오역 인근)",
    "lat": 37.527,
    "lng": 127.039,
    "phone": "010-9164-9690",
    "themes": [
      "라운지",
      "감성주점"
    ],
    "genres": [
      "팝",
      "R&B",
      "힙합"
    ],
    "priceMin": 100000,
    "priceMax": 500000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "압구정로데오에 위치한 감성 라운지. 컬러풀한 인테리어와 트렌디한 분위기에서 프리미엄 음료와 함께 특별한 밤을 즐길 수 있습니다. 합리적인 주대로 인기 있는 곳입니다.",
    "tips": [
      "압구정로데오역 인근",
      "게스트 무료입장 가능 (사전 예약)",
      "MD 하준: 010-9164-9690",
      "테이블 예약 필수 — 사전 문의 권장"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "컬러라운지는 서울 강남에 위치한 감성 라운지입니다."
  },
  {
    "slug": "daegu-babamba",
    "nameKo": "대구바밤바나이트",
    "region": "대구",
    "city": "대구",
    "address": "대구광역시 달서구 달구벌대로 1910 B1",
    "lat": 35.858,
    "lng": 128.563,
    "phone": "010-5840-8066",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "대구 달서구 달구벌대로에 위치한 대구 대표 나이트클럽. 지하 1층의 넓은 공간에서 7080 음악과 EDM을 즐길 수 있으며, 전문 웨이터의 부킹 서비스가 인기입니다.",
    "tips": [
      "달구벌대로 1910 지하 1층",
      "주차 가능",
      "웨이터 신동: 010-7610-8922",
      "웨이터 손흥민: 010-2109-0014",
      "예약문의: 010-5840-8066"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "대구바밤바나이트는 대구 달서구 달구벌대로 1910 B1에 위치한 나이트클럽입니다."
  },
  {
    "slug": "doksan-kookbingwan",
    "nameKo": "독산동국빈관나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 금천구 범안로 1209 협진빌딩 4층 (독산동 293-5)",
    "lat": 37.4675,
    "lng": 126.8962,
    "phone": "02-895-2245",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 금천구 독산동에 위치한 나이트클럽. 협진빌딩 4층에 위치하며, 7080 음악과 트로트를 중심으로 소셜댄스를 즐길 수 있는 전통 있는 나이트클럽입니다.",
    "tips": [
      "웨이터 오리: 010-5859-1908",
      "웨이터 나비: 010-2495-9703",
      "예약문의: 02-895-2245"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "독산동국빈관나이트는 서울 금천구 범안로 1209 협진빌딩 4층에 위치한 나이트클럽입니다."
  },
  {
    "slug": "gangnam-race",
    "nameKo": "강남레이스클럽",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 서초구 강남대로 597 B1 (신사역 4번출구)",
    "lat": 37.5165,
    "lng": 127.0196,
    "phone": "010-4459-1355",
    "instagram": "https://www.instagram.com/clubraceseoul_official/",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "일렉트로닉"
    ],
    "priceMin": 1000000,
    "priceMax": 7000000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": false,
    "summary": "강남 신사역 4번출구 인근에 위치한 대형 프리미엄 클럽. 일렉존과 힙합존이 공존하며, 국내외 유명 DJ들의 공연이 매주 진행됩니다. 강남 대표 클럽 중 하나로 목~일 매일 오픈합니다.",
    "tips": [
      "부스: 1,000,000원~",
      "준메인 테이블: 3,000,000원~",
      "메인 자리: 7,000,000원~",
      "입장료: 20,000원",
      "MD 유석: 010-3846-4018",
      "MD 스피드찬이: 010-2675-5176",
      "MD 이쫑쫑: 010-9950-2395",
      "MD 희찬: 010-2364-8197",
      "MD 현우: 010-4648-7657"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "목·금·토·일 23:00~11:00",
    "peakTime": "01:00~04:00",
    "bodyContent": "강남레이스클럽은 서울 서초구 강남대로 597 B1에 위치한 대형 프리미엄 클럽입니다."
  },
  {
    "slug": "gangnam-sound",
    "nameKo": "강남사운드클럽",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 도산대로 114 B1",
    "lat": 37.517,
    "lng": 127.023,
    "phone": "010-9173-5811",
    "instagram": "https://www.instagram.com/clubsound_official/",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "일렉트로닉"
    ],
    "priceMin": 500000,
    "priceMax": 5000000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": false,
    "summary": "강남 도산대로에 위치한 프리미엄 클럽. 레이스클럽과 같은 운영진이 운영하며, 최신식 인테리어와 고급 음향 시스템을 자랑합니다. 국내외 유명 DJ들이 매주 출연하는 강남 클럽씬의 핵심 스팟입니다.",
    "tips": [
      "입장료: 20,000원",
      "부스/테이블 예약 필수 (2병 미니멈 ~600,000원~)",
      "MD 윤건: 010-9288-4419",
      "MD 병규: 010-7243-3101",
      "대표전화: 010-9173-5811"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "목·금·토·일 23:00~08:00",
    "peakTime": "01:00~04:00",
    "bodyContent": "강남사운드클럽은 서울 강남구 도산대로 114 B1에 위치한 프리미엄 클럽입니다."
  },
  {
    "slug": "gangseo-hobak",
    "nameKo": "강서호박나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강서구 화곡로 354-10 칼튼호텔 B1 (화곡동 1110-3)",
    "lat": 37.541,
    "lng": 126.839,
    "phone": "010-5329-3412",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "서울 강서구 화곡동 칼튼호텔 지하 1층에 위치한 나이트클럽. 까치산역 인근으로 교통이 편리하며, 넓은 홀과 부스를 갖추고 있습니다.",
    "tips": [
      "까치산역 인근 도보 접근 가능",
      "칼튼호텔 지하 1층",
      "웨이터 나이키: 010-5329-3412",
      "예약문의: 010-5329-3412"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "강서호박나이트는 서울 강서구 화곡로 354-10 칼튼호텔 B1에 위치한 나이트클럽입니다."
  },
  {
    "slug": "gildong-chance",
    "nameKo": "길동찬스나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강동구 천호대로 1135 B1",
    "lat": 37.535,
    "lng": 127.14,
    "phone": "010-3583-1237",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 265000,
    "priceMax": 390000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 강동구 길동에 위치한 나이트클럽. 천호대로 1135 지하 1층에 위치하며, 부스와 룸을 갖추고 있어 프라이빗한 유흥을 즐길 수 있습니다.",
    "tips": [
      "부스: 265,000원~",
      "룸: 390,000원~",
      "웨이터 박카스: 010-3583-1237",
      "예약문의: 010-3583-1237"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "길동찬스나이트는 서울 강동구 천호대로 1135에 위치한 나이트클럽입니다."
  },
  {
    "slug": "hype-lounge",
    "nameKo": "하입라운지",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 압구정로데오 (압구정로데오역 인근)",
    "lat": 37.527,
    "lng": 127.039,
    "phone": "010-5645-6786",
    "themes": [
      "라운지",
      "감성주점"
    ],
    "genres": [
      "팝",
      "R&B",
      "힙합"
    ],
    "priceMin": 100000,
    "priceMax": 500000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "압구정로데오에 위치한 프리미엄 감성 라운지. 세련된 인테리어와 고급스러운 분위기에서 칵테일과 음악을 즐길 수 있는 핫플레이스입니다. 게스트 무료입장 가능.",
    "tips": [
      "압구정로데오역 인근",
      "게스트 무료입장 가능 (사전 예약)",
      "MD 은혁: 010-5645-6786",
      "MD 상명: 010-3935-1370",
      "테이블 예약 필수 — 사전 문의 권장"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "하입라운지는 서울 강남에 위치한 프리미엄 감성 라운지입니다."
  },
  {
    "slug": "ilsan-shampoo",
    "nameKo": "일산샴푸나이트",
    "region": "경기",
    "city": "고양",
    "address": "경기도 고양시 일산동구 마두동 (마두역 8번출구, 9층)",
    "lat": 37.6533,
    "lng": 126.7716,
    "phone": "010-9007-0963",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "일산 마두역 8번출구 인근 9층에 위치한 대형 나이트클럽. 50~60개 룸, 20여개 부스, 80여개 테이블을 갖춘 대규모 시설이며, 20~50대까지 폭넓은 연령층이 방문합니다.",
    "tips": [
      "마두역 8번출구 도보 접근",
      "건물 1층~지하5층 주차 가능",
      "50~60개 룸, 20여개 부스, 80여개 테이블 보유",
      "매주 테마 파티 및 특별 이벤트 진행",
      "예약문의: 010-9007-0963",
      "웨이터 곰: 010-5271-5927",
      "웨이터 뽀로로: 010-8368-1880"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/h/"
    ],
    "operatingHours": "금·토 21:00~06:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "일산샴푸나이트는 경기도 고양시 일산동구 마두역 인근에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "incheon-arabian",
    "nameKo": "인천아라비안나이트",
    "region": "인천",
    "city": "인천",
    "address": "인천광역시 계양구 도두리로 14 맘모스빌딩 4~7층",
    "lat": 37.5379,
    "lng": 126.7312,
    "phone": "010-2133-1346",
    "themes": [
      "클럽",
      "DJ파티",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 39000,
    "priceMax": 49000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "인천 계양구에 위치한 인천 최대 규모 프리미엄 나이트클럽. 4개 층, 수십 개 BOX룸과 VIP룸, 유리부스, 프라이빗 테이블을 갖추고 있습니다. 여성 무료입장 이벤트 진행.",
    "tips": [
      "입장료: 평일 남 49,000원 / 여 39,000원 (맥주 기본)",
      "부스: 평일 215,000~245,000원 / 주말 308,000원 (양주+안주+음료 포함)",
      "룸: 평일 300,000원~ / 주말 392,000원~",
      "여성 무료입장 이벤트 수시 진행",
      "예약문의: 010-2133-1346",
      "웨이터 늑대: 010-8691-5547",
      "웨이터 조조: 010-9343-0005",
      "웨이터 토마토: 010-4400-3557"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/k/"
    ],
    "operatingHours": "금·토 21:00~06:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "인천아라비안나이트는 인천광역시 계양구 도두리로 14 맘모스빌딩에 위치한 프리미엄 나이트클럽입니다."
  },
  {
    "slug": "intro-lounge",
    "nameKo": "인트로라운지",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 신사동 662-17 B1 (압구정로데오역 5번출구)",
    "lat": 37.527,
    "lng": 127.039,
    "phone": "010-7289-4833",
    "themes": [
      "라운지",
      "감성주점"
    ],
    "genres": [
      "힙합",
      "R&B",
      "팝"
    ],
    "priceMin": 100000,
    "priceMax": 500000,
    "dressCode": "스마트캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "압구정로데오 신사동에 위치한 전설적인 힙합 라운지. 지하 1층의 감성적인 공간에서 유명 DJ들의 힙합 음악을 즐길 수 있습니다. 4~6인 룸형 부스와 2인 테이블 등 다양한 좌석을 갖추고 있습니다.",
    "tips": [
      "압구정로데오역 5번출구",
      "게스트 무료입장 가능 (사전 예약)",
      "드레스코드: 트레이닝복·모자·슬리퍼 불가",
      "MD 정환: 010-7289-4833",
      "주말 테이블 사전 예약 필수"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 22:00~06:00",
    "peakTime": "23:00~02:00",
    "bodyContent": "인트로라운지는 서울 강남에 위치한 프리미엄 감성 라운지입니다."
  },
  {
    "slug": "itaewon-waikiki",
    "nameKo": "이태원와이키키유토피아클럽",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 용산구 이태원로 173-7 B1",
    "lat": 37.5345,
    "lng": 126.995,
    "phone": "010-9636-1874",
    "themes": [
      "클럽",
      "DJ파티",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 200000,
    "priceMax": 1000000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "이태원에 위치한 인기 클럽. 이태원로 173-7 지하 1층에 위치하며, 다양한 장르의 음악과 함께 외국인과 한국인이 함께 즐기는 글로벌한 분위기가 특징입니다.",
    "tips": [
      "이태원로 173-7 지하 1층",
      "MD 성욱: 010-9636-1874",
      "금·토·일 영업"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토·일 21:00~08:00",
    "peakTime": "00:00~04:00",
    "bodyContent": "이태원와이키키유토피아클럽은 서울 용산구 이태원로 173-7 B1에 위치한 클럽입니다."
  },
  {
    "slug": "nowon-hobak",
    "nameKo": "노원호박나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 노원구 노해로 456 동방빌딩 B1~B2",
    "lat": 37.6552,
    "lng": 127.0612,
    "phone": "010-3171-9695",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "서울 노원구 상계동에 위치한 대표 나이트클럽. 동방빌딩 지하 1~2층에 걸친 넓은 공간으로 룸, 부스, 테이블을 갖추고 있습니다. 여성 무료입장이며 풍성한 주류 셋팅이 포함됩니다.",
    "tips": [
      "여성 무료입장",
      "풍성한 주류 셋팅 (소주·맥주·양주 외 다수)",
      "단체 예약 시 특별 혜택",
      "웨이터 까치: 010-8982-3381",
      "예약문의: 010-3171-9695"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "노원호박나이트는 서울 노원구 노해로 456 동방빌딩에 위치한 나이트클럽입니다."
  },
  {
    "slug": "nowon-star",
    "nameKo": "노원스타나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 노원구 상계동 (노원역 인근)",
    "lat": 37.6552,
    "lng": 127.0612,
    "phone": "010-8005-3762",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 노원구에 위치한 나이트클럽. 노원역 인근의 편리한 접근성과 전문 웨이터의 부킹 서비스로 인기 있는 나이트클럽입니다.",
    "tips": [
      "노원역 인근",
      "웨이터 돼지: 010-8005-3762",
      "예약문의: 010-8005-3762"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "노원스타나이트는 서울 노원구 상계동에 위치한 나이트클럽입니다."
  },
  {
    "slug": "paju-skydome",
    "nameKo": "파주야당스카이돔나이트",
    "region": "경기",
    "city": "파주",
    "address": "경기도 파주시 소리천로 25 유은7차 B구역 (야당동 1083)",
    "lat": 37.7136,
    "lng": 126.7615,
    "phone": "031-945-8989",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 10000,
    "priceMax": 15000,
    "dressCode": "캐주얼 (깔끔하게)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "파주 야당동에 위치한 대형 나이트클럽. 입장료가 평일 1만원/주말 1.5만원으로 합리적이며, 매일 영업합니다. 넓은 스카이돔 구조 홀과 라운지가 분리되어 있습니다.",
    "tips": [
      "입장료: 평일 10,000원 / 주말 15,000원",
      "음료 10,000원부터",
      "매일 21시~06시 영업 (일요일은 05시까지)",
      "네비 검색: '유은7차' 검색",
      "대표전화: 031-945-8989"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/f/"
    ],
    "operatingHours": "매일 21:00~06:00 (일요일 ~05:00)",
    "peakTime": "23:00~01:00",
    "bodyContent": "파주야당스카이돔나이트는 경기도 파주시 소리천로 25에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "sangbong-hankookgwan",
    "nameKo": "상봉동한국관나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 중랑구 상봉동 91-1 (상봉역 2번출구 도보 3분)",
    "lat": 37.5966,
    "lng": 127.0855,
    "phone": "010-5443-6475",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 중랑구 상봉역 2번출구 도보 3분 거리에 위치한 나이트클럽. 테이블/부스 5~10만원, 룸은 40만원(위스키 세트 포함)부터 이용 가능합니다. 공휴일 전날에는 예약 필수.",
    "tips": [
      "상봉역 2번출구에서 도보 3분",
      "테이블/부스: 5~10만원",
      "룸: 위스키 세트 포함 40만원~",
      "공휴일 전날에는 조기 마감 — 사전 예약 필수",
      "예약문의: 010-5443-6475 또는 010-5243-7994",
      "웨이터 박카스: 010-9418-9222",
      "웨이터 황소: 010-5476-6297",
      "웨이터 오십원: 010-9986-5137",
      "웨이터 홍길동: 010-4662-4409",
      "웨이터 돼지: 010-9265-2612",
      "웨이터 까치: 010-6342-1860"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/j/",
      "/n/",
      "/o/",
      "/p/",
      "/q/"
    ],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "상봉동한국관나이트는 서울 중랑구 상봉동 91-1에 위치한 나이트클럽입니다."
  },
  {
    "slug": "seongnam-shampoo",
    "nameKo": "성남샴푸나이트",
    "region": "경기",
    "city": "성남",
    "address": "경기도 성남시 중원구 광명로 21 (성남동 3182)",
    "lat": 37.438,
    "lng": 127.138,
    "phone": "010-9779-2527",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "경기도 성남시 중원구 모란역 인근에 위치한 나이트클럽. 대중교통 접근성이 뛰어나며, 합리적인 가격으로 즐길 수 있는 나이트클럽입니다.",
    "tips": [
      "모란역 인근 도보 접근 가능",
      "주차 가능",
      "웨이터 딸기: 010-9779-2527",
      "웨이터 손흥민: 010-8405-2765"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "성남샴푸나이트는 경기도 성남시 중원구 광명로 21에 위치한 나이트클럽입니다."
  },
  {
    "slug": "sinlim-grandprix",
    "nameKo": "신림그랑프리나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 관악구 신림로 340 (신림동 1422-5)",
    "lat": 37.4842,
    "lng": 126.9293,
    "phone": "010-5934-2617",
    "instagram": "https://www.instagram.com/club_grangpri.official/",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼 (깔끔하게)",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "신림역 인근 관악구 신림로에 위치한 클럽형 나이트. 평일·주말 모두 운영하며, 50~60개 룸과 부스를 갖춘 대형 시설입니다.",
    "tips": [
      "신림역에서 도보 접근 가능",
      "평일도 영업 (18시~04시)",
      "주말은 06시까지 연장 운영",
      "예약문의: 010-5934-2617",
      "주차장 없음 — 대중교통 이용 권장",
      "웨이터 둘리: 010-3009-4019",
      "웨이터 이쁜이: 010-2062-8147",
      "웨이터 손흥민: 010-8140-1622",
      "웨이터 엄지: 010-6851-9949"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/c/"
    ],
    "operatingHours": "평일 18:00~04:00 / 주말 18:00~06:00",
    "peakTime": "23:00~02:00",
    "bodyContent": "신림그랑프리나이트는 서울 관악구 신림로 340에 위치한 나이트클럽입니다."
  },
  {
    "slug": "suwon-chance-dome",
    "nameKo": "수원찬스돔나이트",
    "region": "경기",
    "city": "수원",
    "address": "경기도 수원시 권선구 권선로 673 (권선동 1019-9)",
    "lat": 37.2576,
    "lng": 127.0286,
    "phone": "031-990-4553",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼 (깔끔한 복장 권장)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "수원 권선동에 위치한 대형 나이트클럽. 20대~40대까지 폭넓은 연령층이 방문하며, 넓고 화려한 인테리어와 수준 높은 DJ 음악, VIP룸을 갖추고 있습니다.",
    "tips": [
      "에이스 예약: 010-8634-4715",
      "대표전화: 031-990-4553",
      "12시 이전 입장 여성 고객 이벤트가 있을 수 있음",
      "VIP룸 및 대형 플로어 보유",
      "주말/공휴일에는 지역 외 방문객도 많은 편",
      "웨이터 아줌마: 010-5410-7337",
      "웨이터 천사: 010-9791-2774",
      "웨이터 바나나: 010-5199-8184",
      "웨이터 손흥민: 010-2793-5959",
      "웨이터 주전자: 010-7420-1201",
      "웨이터 장미: 010-7920-7754"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/b/"
    ],
    "operatingHours": "연중무휴 (월·화 휴무일 수 있음, 전화확인 권장)",
    "peakTime": "23:00~01:00",
    "bodyContent": "수원찬스돔나이트는 수원시 권선구 권선로 673에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "suwon-korea",
    "nameKo": "수원코리아나이트",
    "region": "경기",
    "city": "수원",
    "address": "경기도 수원시 팔달구 인계동 1016-7 B1",
    "lat": 37.2636,
    "lng": 127.0286,
    "phone": "070-8065-1219",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "경기도 수원시 팔달구 인계동에 위치한 나이트클럽. 지하 1층에 위치하며, 7080 음악과 트로트를 중심으로 소셜댄스를 즐길 수 있습니다.",
    "tips": [
      "인계동 1016-7 지하 1층",
      "웨이터 오백원: 010-9096-2145",
      "예약문의: 070-8065-1219"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "수원코리아나이트는 경기도 수원시 팔달구 인계동 1016-7에 위치한 나이트클럽입니다."
  },
  {
    "slug": "suyu-shampoo",
    "nameKo": "수유샴푸나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강북구 수유동 (수유역 근처)",
    "lat": 37.638,
    "lng": 127.025,
    "phone": "010-9571-5576",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 290000,
    "priceMax": 440000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 강북구 수유역 인근에 위치한 인기 나이트클럽. 부킹 잘되기로 유명하며, 룸과 부스를 갖추고 있어 단체 모임에도 적합합니다. 전문 웨이터가 최상의 서비스를 제공합니다.",
    "tips": [
      "룸 가격: 평일 290,000원 / 금요일 390,000원 / 토요일 440,000원",
      "수유역에서 도보 접근 가능",
      "웨이터 이등병: 010-5101-5134",
      "웨이터 로또: 010-4738-5088",
      "웨이터 오렌지: 010-7433-3172",
      "예약문의: 010-9571-5576"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "수유샴푸나이트는 서울 강북구 수유동에 위치한 나이트클럽입니다."
  },
  {
    "slug": "ulsan-champion",
    "nameKo": "울산챔피언나이트",
    "region": "울산",
    "city": "울산",
    "address": "울산광역시 남구 삼산동 1559-17 (정동로 75) 1층",
    "lat": 35.5406,
    "lng": 129.3438,
    "phone": "010-4674-5602",
    "instagram": "https://www.instagram.com/championnightclub/",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "울산 남구 삼산동에 위치한 울산 대표 나이트클럽. 정동로 75 1층에 위치하며, 국내외 유명 DJ 공연과 부킹 시스템을 갖추고 있습니다.",
    "tips": [
      "울산 남구 삼산동 정동로 75 1층",
      "예약문의: 010-4674-5602",
      "국내외 유명 DJ 초청 이벤트 진행",
      "주차 가능",
      "방문 전 전화로 영업일/시간 확인 추천"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/g/"
    ],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "23:00~01:00",
    "bodyContent": "울산챔피언나이트는 울산광역시 남구 정동로 75에 위치한 나이트클럽입니다."
  }
];

export const regions = ["경기","대구","부산","서울","울산","인천","충남"] as const;

export const citiesByRegion: Record<string, string[]> = {
  "경기": [
    "고양",
    "파주",
    "성남",
    "수원"
  ],
  "대구": [
    "대구"
  ],
  "부산": [
    "부산"
  ],
  "서울": [
    "서울"
  ],
  "울산": [
    "울산"
  ],
  "인천": [
    "인천"
  ],
  "충남": [
    "천안"
  ]
};

export const allThemes = ["7080","DJ파티","감성주점","강남","라운지","소셜댄스","클럽"] as const;

export const legacyRedirects: Record<string, string> = {
  "/d/": "/club/cheongdam-h2o/",
  "/h/": "/club/ilsan-shampoo/",
  "/k/": "/club/incheon-arabian/",
  "/f/": "/club/paju-skydome/",
  "/j/": "/club/sangbong-hankookgwan/",
  "/n/": "/club/sangbong-hankookgwan/",
  "/o/": "/club/sangbong-hankookgwan/",
  "/p/": "/club/sangbong-hankookgwan/",
  "/q/": "/club/sangbong-hankookgwan/",
  "/c/": "/club/sinlim-grandprix/",
  "/b/": "/club/suwon-chance-dome/",
  "/g/": "/club/ulsan-champion/"
};
