// AUTO-GENERATED by scripts/build-venues-index.ts — DO NOT EDIT
// Generated at: 2026-02-13T22:34:35.718Z

import type { Venue } from "./types";

export const venues: Venue[] = [
  {
    "slug": "cheongdam-h2o",
    "nameKo": "청담H2O나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 강남구 청담동 53-8 리베라호텔 B1",
    "lat": 37.5247,
    "lng": 127.047,
    "phone": "010-7404-6603",
    "themes": [
      "강남",
      "클럽",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "하우스"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "스마트캐주얼 이상 (드레스코드 엄격)",
    "parking": true,
    "beginnerFriendly": false,
    "summary": "강남 청담동 리베라호텔 지하에 위치한 프리미엄 나이트클럽. 예약제로 운영되며, 룸/부스 예약은 사전 연락 필수. 20~30대 직장인 중심의 고급 클러빙 문화를 이끌고 있습니다.",
    "tips": [
      "리베라호텔 지하 1층에 위치",
      "예약제 운영 — 사전 전화 필수: 010-7404-6603",
      "드레스코드 엄격 — 정장/원피스 권장",
      "테이블/부스/룸 예약 시 최소 주류 주문 필요",
      "발레파킹 가능 (유료)"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/d/"
    ],
    "operatingHours": "금·토 22:00~05:00 (예약제)",
    "peakTime": "00:00~02:00",
    "bodyContent": "청담H2O나이트는 서울 강남구 청담동 리베라호텔 B1에 위치한 프리미엄 나이트클럽입니다."
  },
  {
    "slug": "ilsan-shampoo",
    "nameKo": "일산샴푸나이트",
    "region": "경기",
    "city": "고양",
    "address": "경기도 고양시 일산동구 마두동 (마두역 8번출구, 9층)",
    "lat": 37.6533,
    "lng": 126.7716,
    "phone": "010-9007-0963",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "일산 마두역 8번출구 인근 9층에 위치한 대형 나이트클럽. 50~60개 룸, 20여개 부스, 80여개 테이블을 갖춘 대규모 시설이며, 20~50대까지 폭넓은 연령층이 방문합니다.",
    "tips": [
      "마두역 8번출구 도보 접근",
      "건물 1층~지하5층 주차 가능",
      "50~60개 룸, 20여개 부스, 80여개 테이블 보유",
      "매주 테마 파티 및 특별 이벤트 진행",
      "예약문의: 010-9007-0963"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/h/"
    ],
    "operatingHours": "금·토 21:00~06:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "일산샴푸나이트는 경기도 고양시 일산동구 마두역 인근에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "incheon-arabian",
    "nameKo": "인천아라비안나이트",
    "region": "인천",
    "city": "인천",
    "address": "인천광역시 계양구 도두리로 14 맘모스빌딩 4~7층",
    "lat": 37.5379,
    "lng": 126.7312,
    "phone": "010-2133-1346",
    "themes": [
      "클럽",
      "DJ파티",
      "라운지"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 39000,
    "priceMax": 49000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "인천 계양구에 위치한 인천 최대 규모 프리미엄 나이트클럽. 4개 층, 수십 개 BOX룸과 VIP룸, 유리부스, 프라이빗 테이블을 갖추고 있습니다. 여성 무료입장 이벤트 진행.",
    "tips": [
      "입장료: 평일 남 49,000원 / 여 39,000원 (맥주 기본)",
      "부스: 평일 215,000~245,000원 / 주말 308,000원 (양주+안주+음료 포함)",
      "룸: 평일 300,000원~ / 주말 392,000원~",
      "여성 무료입장 이벤트 수시 진행",
      "예약문의: 010-2133-1346"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/k/"
    ],
    "operatingHours": "금·토 21:00~06:00 (전화확인 권장)",
    "peakTime": "23:00~02:00",
    "bodyContent": "인천아라비안나이트는 인천광역시 계양구 도두리로 14 맘모스빌딩에 위치한 프리미엄 나이트클럽입니다."
  },
  {
    "slug": "paju-skydome",
    "nameKo": "파주야당스카이돔나이트",
    "region": "경기",
    "city": "파주",
    "address": "경기도 파주시 소리천로 25 유은7차 B구역 (야당동 1083)",
    "lat": 37.7136,
    "lng": 126.7615,
    "phone": "031-945-8989",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 10000,
    "priceMax": 15000,
    "dressCode": "캐주얼 (깔끔하게)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "파주 야당동에 위치한 대형 나이트클럽. 입장료가 평일 1만원/주말 1.5만원으로 합리적이며, 매일 영업합니다. 넓은 스카이돔 구조 홀과 라운지가 분리되어 있습니다.",
    "tips": [
      "입장료: 평일 10,000원 / 주말 15,000원",
      "음료 10,000원부터",
      "매일 21시~06시 영업 (일요일은 05시까지)",
      "네비 검색: '유은7차' 검색",
      "대표전화: 031-945-8989"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/f/"
    ],
    "operatingHours": "매일 21:00~06:00 (일요일 ~05:00)",
    "peakTime": "23:00~01:00",
    "bodyContent": "파주야당스카이돔나이트는 경기도 파주시 소리천로 25에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "sangbong-hankookgwan",
    "nameKo": "상봉동한국관나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 중랑구 상봉동 91-1 (상봉역 2번출구 도보 3분)",
    "lat": 37.5966,
    "lng": 127.0855,
    "phone": "010-5443-6475",
    "themes": [
      "7080",
      "소셜댄스"
    ],
    "genres": [
      "7080",
      "트로트",
      "발라드"
    ],
    "priceMin": 50000,
    "priceMax": 100000,
    "dressCode": "세미캐주얼",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "서울 중랑구 상봉역 2번출구 도보 3분 거리에 위치한 나이트클럽. 테이블/부스 5~10만원, 룸은 40만원(위스키 세트 포함)부터 이용 가능합니다. 공휴일 전날에는 예약 필수.",
    "tips": [
      "상봉역 2번출구에서 도보 3분",
      "테이블/부스: 5~10만원",
      "룸: 위스키 세트 포함 40만원~",
      "공휴일 전날에는 조기 마감 — 사전 예약 필수",
      "예약문의: 010-5443-6475 또는 010-5243-7994"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/j/",
      "/n/",
      "/o/",
      "/p/",
      "/q/"
    ],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "22:30~01:00",
    "bodyContent": "상봉동한국관나이트는 서울 중랑구 상봉동 91-1에 위치한 나이트클럽입니다."
  },
  {
    "slug": "sinlim-grandprix",
    "nameKo": "신림그랑프리나이트",
    "region": "서울",
    "city": "서울",
    "address": "서울특별시 관악구 신림로 340 (신림동 1422-5)",
    "lat": 37.4842,
    "lng": 126.9293,
    "phone": "010-5934-2617",
    "instagram": "https://www.instagram.com/club_grangpri.official/",
    "themes": [
      "클럽",
      "DJ파티"
    ],
    "genres": [
      "EDM",
      "힙합",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼 (깔끔하게)",
    "parking": false,
    "beginnerFriendly": true,
    "summary": "신림역 인근 관악구 신림로에 위치한 클럽형 나이트. 평일·주말 모두 운영하며, 50~60개 룸과 부스를 갖춘 대형 시설입니다.",
    "tips": [
      "신림역에서 도보 접근 가능",
      "평일도 영업 (18시~04시)",
      "주말은 06시까지 연장 운영",
      "예약문의: 010-5934-2617",
      "주차장 없음 — 대중교통 이용 권장"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/c/"
    ],
    "operatingHours": "평일 18:00~04:00 / 주말 18:00~06:00",
    "peakTime": "23:00~02:00",
    "bodyContent": "신림그랑프리나이트는 서울 관악구 신림로 340에 위치한 나이트클럽입니다."
  },
  {
    "slug": "suwon-chance-dome",
    "nameKo": "수원찬스돔나이트",
    "region": "경기",
    "city": "수원",
    "address": "경기도 수원시 권선구 권선로 673 (권선동 1019-9)",
    "lat": 37.2576,
    "lng": 127.0286,
    "phone": "031-990-4553",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼 (깔끔한 복장 권장)",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "수원 권선동에 위치한 대형 나이트클럽. 20대~40대까지 폭넓은 연령층이 방문하며, 넓고 화려한 인테리어와 수준 높은 DJ 음악, VIP룸을 갖추고 있습니다.",
    "tips": [
      "에이스 예약: 010-8634-4715",
      "대표전화: 031-990-4553",
      "12시 이전 입장 여성 고객 이벤트가 있을 수 있음",
      "VIP룸 및 대형 플로어 보유",
      "주말/공휴일에는 지역 외 방문객도 많은 편"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/b/"
    ],
    "operatingHours": "연중무휴 (월·화 휴무일 수 있음, 전화확인 권장)",
    "peakTime": "23:00~01:00",
    "bodyContent": "수원찬스돔나이트는 수원시 권선구 권선로 673에 위치한 대형 나이트클럽입니다."
  },
  {
    "slug": "ulsan-champion",
    "nameKo": "울산챔피언나이트",
    "region": "울산",
    "city": "울산",
    "address": "울산광역시 남구 삼산동 1559-17 (정동로 75) 1층",
    "lat": 35.5406,
    "lng": 129.3438,
    "phone": "010-4674-5602",
    "instagram": "https://www.instagram.com/championnightclub/",
    "themes": [
      "7080",
      "소셜댄스",
      "DJ파티"
    ],
    "genres": [
      "7080",
      "트로트",
      "EDM",
      "팝"
    ],
    "priceMin": 30000,
    "priceMax": 50000,
    "dressCode": "세미캐주얼",
    "parking": true,
    "beginnerFriendly": true,
    "summary": "울산 남구 삼산동에 위치한 울산 대표 나이트클럽. 정동로 75 1층에 위치하며, 국내외 유명 DJ 공연과 부킹 시스템을 갖추고 있습니다.",
    "tips": [
      "울산 남구 삼산동 정동로 75 1층",
      "예약문의: 010-4674-5602",
      "국내외 유명 DJ 초청 이벤트 진행",
      "주차 가능",
      "방문 전 전화로 영업일/시간 확인 추천"
    ],
    "lastVerifiedAt": "2026-02-13",
    "legacyPaths": [
      "/g/"
    ],
    "operatingHours": "금·토 21:00~04:00 (전화확인 권장)",
    "peakTime": "23:00~01:00",
    "bodyContent": "울산챔피언나이트는 울산광역시 남구 정동로 75에 위치한 나이트클럽입니다."
  }
];

export const regions = ["경기","서울","울산","인천"] as const;

export const citiesByRegion: Record<string, string[]> = {
  "경기": [
    "고양",
    "파주",
    "수원"
  ],
  "서울": [
    "서울"
  ],
  "울산": [
    "울산"
  ],
  "인천": [
    "인천"
  ]
};

export const allThemes = ["7080","DJ파티","강남","라운지","소셜댄스","클럽"] as const;

export const legacyRedirects: Record<string, string> = {
  "/d/": "/club/cheongdam-h2o/",
  "/h/": "/club/ilsan-shampoo/",
  "/k/": "/club/incheon-arabian/",
  "/f/": "/club/paju-skydome/",
  "/j/": "/club/sangbong-hankookgwan/",
  "/n/": "/club/sangbong-hankookgwan/",
  "/o/": "/club/sangbong-hankookgwan/",
  "/p/": "/club/sangbong-hankookgwan/",
  "/q/": "/club/sangbong-hankookgwan/",
  "/c/": "/club/sinlim-grandprix/",
  "/b/": "/club/suwon-chance-dome/",
  "/g/": "/club/ulsan-champion/"
};
